# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: PoliCheck@1
  inputs:
    targetType: 'F'
    targetArgument: '$(Build.SourcesDirectory)'
- task: PublishSecurityAnalysisLogs@3
  inputs:
    ArtifactName: 'CodeAnalysisLogs'
    ArtifactType: 'Container'
    PublishProcessedResults: true
    AllTools: true
    ToolLogsNotFoundAction: 'Standard'
- task: SdtReport@2
  inputs:
    GdnExportHtmlFile: true
    GdnExportAllTools: true